//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivedNote
    {
        public string ReceivedID { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public string ProductID { get; set; }
        public double RPrice { get; set; }
        public int Quantity { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
